version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:15"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:15"
    open-pull-requests-limit: 10
