version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:15"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      babel:
        patterns:
          - "@babel/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      typescript-types:
        patterns:
          - "@types/node"
          - "@types/react"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:15"
    open-pull-requests-limit: 10
