stages:
  - install
  - test

# Supported Node versions

.node10: &node10
  image: node:10

.node12: &node12
  image: node:12

.node13: &node13
  image: node:13

# Install

.install:
  stage: install
  script:
    - yarn install
  cache:
    paths:
      - node_modules

install_node10:
  <<: [*node10]
  extends: .install
  cache:
    key: lightbase-node10

install_node12:
  <<: [*node12]
  extends: .install
  cache:
    key: lightbase-node12

install_node13:
  <<: [*node13]
  extends: .install
  cache:
    key: lightbase-node13

# Test

.build_lint_test:
  stage: test
  cache:
    paths:
      - node_modules
    policy: pull
  script:
    - yarn build
    - yarn lint
    - yarn test

build_lint_test_node10:
  <<: [*node10]
  extends: .build_lint_test
  cache:
    key: lightbase-node10

build_lint_test_node12:
  <<: [*node12]
  extends: .build_lint_test
  cache:
    key: lightbase-node12

build_lint_test_node13:
  <<: [*node13]
  extends: .build_lint_test
  cache:
    key: lightbase-node13
