stages:
  - test

# Supported Node versions
.node14: &node14
  image: node:14

# Test

.build_lint_test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn lbu lint
    - yarn lbu test

build_lint_test_node14:
  <<: [*node14]
  extends: .build_lint_test
  cache:
    key: lightbase-node14
