theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: Changelog
    url: changelog.html
  - title: Getting started
    url: getting-started.html
  - title: Cli
    url: cli.html
  - title: Code generation
    url: code-gen.html
  - title: Insight
    url: insight.html
  - title: Server
    url: server.html
  - title: Store
    url: store.html
  - title: Lint config
    url: lint-config.html
  - title: Environment
    url: env.html
  - title: How to
    url: how-to.html
  - title: Contributing
    url: contributing.html
