name: Create a release on tag

on:
  push:
    tags:
      - "*"

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Create release
        run: |
          yarn install
          yarn compas create-release ${{ secrets.COMPAS_GITHUB_TOKEN }}
  sync-docs:
    timeout-minutes: 15
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: compas

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          repository: compasjs/docs
          path: compas-docs
          token: ${{ secrets.COMPAS_GITHUB_TOKEN }}

      - name: Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Create release
        run: |
          cd ./compas-docs
          yarn install
          yarn upgrade --latest --exact --scope @compas
          yarn compas generate
          CI=false yarn compas sync
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: bump compas"
          git push
