name: External PR Checks
on: [pull_request]

env:
  CI: true

jobs:
  external-test:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: Invoke external lbu e2e tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: LBU e2e
          token: ${{ secrets.LBU_E2E_TOKEN }}
          repo: lightbasenl/lbu-e2e
          ref: main
          inputs: '{ "pr": "${{ github.event.pull_request.number }}" }'
